name: Healet Jewellery GitHub Actions CI/CD pipeline

on: [push]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: tf_infra

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Trivy IaC Scan (Terraform)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          scan-ref: tf_infra
          format: "table"
          exit-code: "0" 
          ignore-unfixed: true

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          args: >
            -Dsonar.projectKey=healet-jewellery
            -Dsonar.organization=Healet-Jewellery
      