name: Healet Jewellery GitHub Actions CI/CD pipeline

on: 
  push:
    branches:
      - master     # plan prod
      - feat*      # plan only for non-prod

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_db_username: ${{ secrets.DB_RDS_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_RDS_PASSWORD }}
    defaults:
      run:
        working-directory: tf_infra

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Trivy IaC Scan (Terraform)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          scan-ref: tf_infra
          format: "table"
          exit-code: "0" 
          ignore-unfixed: true

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output
      
      - name: Terraform Show - Resource Summary
        run: terraform show -no-color | grep '^#'
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sajinatamang99_healet-jewellery
            -Dsonar.organization=healet-jewellery
            -Dsonar.branch.name=${{ github.head_ref || github.ref_name }}
